<?php
/**
 * PaymentsApi
 * PHP version 8.1
 *
 * @category Class
 * @package  OPayments\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OPayments API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OPayments\SDK\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use OPayments\SDK\ApiException;
use OPayments\SDK\Configuration;
use OPayments\SDK\FormDataProcessor;
use OPayments\SDK\HeaderSelector;
use OPayments\SDK\ObjectSerializer;

/**
 * PaymentsApi Class Doc Comment
 *
 * @category Class
 * @package  OPayments\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PaymentsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getPayment' => [
            'application/json',
        ],
        'listPayments' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getPayment
     *
     * Получить платёж
     *
     * @param  string $payment_id payment_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPayment'] to see the possible values for this operation
     *
     * @throws \OPayments\SDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OPayments\SDK\Model\PaymentDetails|\OPayments\SDK\Model\Error|\OPayments\SDK\Model\Error|\OPayments\SDK\Model\Error|\OPayments\SDK\Model\Error
     */
    public function getPayment($payment_id, string $contentType = self::contentTypes['getPayment'][0])
    {
        list($response) = $this->getPaymentWithHttpInfo($payment_id, $contentType);
        return $response;
    }

    /**
     * Operation getPaymentWithHttpInfo
     *
     * Получить платёж
     *
     * @param  string $payment_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPayment'] to see the possible values for this operation
     *
     * @throws \OPayments\SDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OPayments\SDK\Model\PaymentDetails|\OPayments\SDK\Model\Error|\OPayments\SDK\Model\Error|\OPayments\SDK\Model\Error|\OPayments\SDK\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function getPaymentWithHttpInfo($payment_id, string $contentType = self::contentTypes['getPayment'][0])
    {
        $request = $this->getPaymentRequest($payment_id, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OPayments\SDK\Model\PaymentDetails',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OPayments\SDK\Model\Error',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\OPayments\SDK\Model\Error',
                        $request,
                        $response,
                    );
                case 404:
                    return $this->handleResponseWithDataType(
                        '\OPayments\SDK\Model\Error',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\OPayments\SDK\Model\Error',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OPayments\SDK\Model\PaymentDetails',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OPayments\SDK\Model\PaymentDetails',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OPayments\SDK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OPayments\SDK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OPayments\SDK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OPayments\SDK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation getPaymentAsync
     *
     * Получить платёж
     *
     * @param  string $payment_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPayment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPaymentAsync($payment_id, string $contentType = self::contentTypes['getPayment'][0])
    {
        return $this->getPaymentAsyncWithHttpInfo($payment_id, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getPaymentAsyncWithHttpInfo
     *
     * Получить платёж
     *
     * @param  string $payment_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPayment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getPaymentAsyncWithHttpInfo($payment_id, string $contentType = self::contentTypes['getPayment'][0])
    {
        $returnType = '\OPayments\SDK\Model\PaymentDetails';
        $request = $this->getPaymentRequest($payment_id, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getPayment'
     *
     * @param  string $payment_id (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getPayment'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getPaymentRequest($payment_id, string $contentType = self::contentTypes['getPayment'][0])
    {

        // verify the required parameter 'payment_id' is set
        if ($payment_id === null || (is_array($payment_id) && count($payment_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $payment_id when calling getPayment'
            );
        }


        $resourcePath = '/payments/{paymentId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($payment_id !== null) {
            $resourcePath = str_replace(
                '{paymentId}',
                ObjectSerializer::toPathValue($payment_id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Signature');
        if ($apiKey !== null) {
            $headers['X-Signature'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Identity');
        if ($apiKey !== null) {
            $headers['X-Identity'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation listPayments
     *
     * Найти платежи
     *
     * @param  string|null $order_id Идентификатор заказа в системе мерчанта. (optional)
     * @param  string[]|null $status status (optional)
     * @param  string|null $payment_method payment_method (optional)
     * @param  int|null $amount_from Не больше amountTo, если он передан. (optional)
     * @param  int|null $amount_to Не меньше amountFrom, если он передан. (optional)
     * @param  \DateTime|null $created_from Не позже createdTo, если он передан. (optional)
     * @param  \DateTime|null $created_to Не раньше createdFrom, если он передан. (optional)
     * @param  \DateTime|null $completed_from Не позже completedTo, если он передан. (optional)
     * @param  \DateTime|null $completed_to Не раньше completedFrom, если он передан. (optional)
     * @param  string|null $failure_code Нормализованный код причины платежа. (optional)
     * @param  string|null $search Поиск по paymentId, orderId и описанию платежа. (optional)
     * @param  string|null $sort sort (optional, default to 'createdAt')
     * @param  string|null $sort_direction sort_direction (optional, default to 'desc')
     * @param  string|null $cursor Непрозрачный курсор из предыдущего ответа. Используйте только с теми же фильтрами и сортировкой. При одинаковом sort key API использует стабильный вторичный ID. (optional)
     * @param  int|null $limit Количество записей в ответе. (optional, default to 20)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listPayments'] to see the possible values for this operation
     *
     * @throws \OPayments\SDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \OPayments\SDK\Model\PaymentList|\OPayments\SDK\Model\Error|\OPayments\SDK\Model\Error|\OPayments\SDK\Model\Error|\OPayments\SDK\Model\Error
     */
    public function listPayments($order_id = null, $status = null, $payment_method = null, $amount_from = null, $amount_to = null, $created_from = null, $created_to = null, $completed_from = null, $completed_to = null, $failure_code = null, $search = null, $sort = 'createdAt', $sort_direction = 'desc', $cursor = null, $limit = 20, string $contentType = self::contentTypes['listPayments'][0])
    {
        list($response) = $this->listPaymentsWithHttpInfo($order_id, $status, $payment_method, $amount_from, $amount_to, $created_from, $created_to, $completed_from, $completed_to, $failure_code, $search, $sort, $sort_direction, $cursor, $limit, $contentType);
        return $response;
    }

    /**
     * Operation listPaymentsWithHttpInfo
     *
     * Найти платежи
     *
     * @param  string|null $order_id Идентификатор заказа в системе мерчанта. (optional)
     * @param  string[]|null $status (optional)
     * @param  string|null $payment_method (optional)
     * @param  int|null $amount_from Не больше amountTo, если он передан. (optional)
     * @param  int|null $amount_to Не меньше amountFrom, если он передан. (optional)
     * @param  \DateTime|null $created_from Не позже createdTo, если он передан. (optional)
     * @param  \DateTime|null $created_to Не раньше createdFrom, если он передан. (optional)
     * @param  \DateTime|null $completed_from Не позже completedTo, если он передан. (optional)
     * @param  \DateTime|null $completed_to Не раньше completedFrom, если он передан. (optional)
     * @param  string|null $failure_code Нормализованный код причины платежа. (optional)
     * @param  string|null $search Поиск по paymentId, orderId и описанию платежа. (optional)
     * @param  string|null $sort (optional, default to 'createdAt')
     * @param  string|null $sort_direction (optional, default to 'desc')
     * @param  string|null $cursor Непрозрачный курсор из предыдущего ответа. Используйте только с теми же фильтрами и сортировкой. При одинаковом sort key API использует стабильный вторичный ID. (optional)
     * @param  int|null $limit Количество записей в ответе. (optional, default to 20)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listPayments'] to see the possible values for this operation
     *
     * @throws \OPayments\SDK\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \OPayments\SDK\Model\PaymentList|\OPayments\SDK\Model\Error|\OPayments\SDK\Model\Error|\OPayments\SDK\Model\Error|\OPayments\SDK\Model\Error, HTTP status code, HTTP response headers (array of strings)
     */
    public function listPaymentsWithHttpInfo($order_id = null, $status = null, $payment_method = null, $amount_from = null, $amount_to = null, $created_from = null, $created_to = null, $completed_from = null, $completed_to = null, $failure_code = null, $search = null, $sort = 'createdAt', $sort_direction = 'desc', $cursor = null, $limit = 20, string $contentType = self::contentTypes['listPayments'][0])
    {
        $request = $this->listPaymentsRequest($order_id, $status, $payment_method, $amount_from, $amount_to, $created_from, $created_to, $completed_from, $completed_to, $failure_code, $search, $sort, $sort_direction, $cursor, $limit, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType(
                        '\OPayments\SDK\Model\PaymentList',
                        $request,
                        $response,
                    );
                case 400:
                    return $this->handleResponseWithDataType(
                        '\OPayments\SDK\Model\Error',
                        $request,
                        $response,
                    );
                case 401:
                    return $this->handleResponseWithDataType(
                        '\OPayments\SDK\Model\Error',
                        $request,
                        $response,
                    );
                case 403:
                    return $this->handleResponseWithDataType(
                        '\OPayments\SDK\Model\Error',
                        $request,
                        $response,
                    );
                case 429:
                    return $this->handleResponseWithDataType(
                        '\OPayments\SDK\Model\Error',
                        $request,
                        $response,
                    );
            }

            

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            return $this->handleResponseWithDataType(
                '\OPayments\SDK\Model\PaymentList',
                $request,
                $response,
            );
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OPayments\SDK\Model\PaymentList',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OPayments\SDK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OPayments\SDK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 403:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OPayments\SDK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OPayments\SDK\Model\Error',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    throw $e;
            }
        

            throw $e;
        }
    }

    /**
     * Operation listPaymentsAsync
     *
     * Найти платежи
     *
     * @param  string|null $order_id Идентификатор заказа в системе мерчанта. (optional)
     * @param  string[]|null $status (optional)
     * @param  string|null $payment_method (optional)
     * @param  int|null $amount_from Не больше amountTo, если он передан. (optional)
     * @param  int|null $amount_to Не меньше amountFrom, если он передан. (optional)
     * @param  \DateTime|null $created_from Не позже createdTo, если он передан. (optional)
     * @param  \DateTime|null $created_to Не раньше createdFrom, если он передан. (optional)
     * @param  \DateTime|null $completed_from Не позже completedTo, если он передан. (optional)
     * @param  \DateTime|null $completed_to Не раньше completedFrom, если он передан. (optional)
     * @param  string|null $failure_code Нормализованный код причины платежа. (optional)
     * @param  string|null $search Поиск по paymentId, orderId и описанию платежа. (optional)
     * @param  string|null $sort (optional, default to 'createdAt')
     * @param  string|null $sort_direction (optional, default to 'desc')
     * @param  string|null $cursor Непрозрачный курсор из предыдущего ответа. Используйте только с теми же фильтрами и сортировкой. При одинаковом sort key API использует стабильный вторичный ID. (optional)
     * @param  int|null $limit Количество записей в ответе. (optional, default to 20)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listPayments'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listPaymentsAsync($order_id = null, $status = null, $payment_method = null, $amount_from = null, $amount_to = null, $created_from = null, $created_to = null, $completed_from = null, $completed_to = null, $failure_code = null, $search = null, $sort = 'createdAt', $sort_direction = 'desc', $cursor = null, $limit = 20, string $contentType = self::contentTypes['listPayments'][0])
    {
        return $this->listPaymentsAsyncWithHttpInfo($order_id, $status, $payment_method, $amount_from, $amount_to, $created_from, $created_to, $completed_from, $completed_to, $failure_code, $search, $sort, $sort_direction, $cursor, $limit, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation listPaymentsAsyncWithHttpInfo
     *
     * Найти платежи
     *
     * @param  string|null $order_id Идентификатор заказа в системе мерчанта. (optional)
     * @param  string[]|null $status (optional)
     * @param  string|null $payment_method (optional)
     * @param  int|null $amount_from Не больше amountTo, если он передан. (optional)
     * @param  int|null $amount_to Не меньше amountFrom, если он передан. (optional)
     * @param  \DateTime|null $created_from Не позже createdTo, если он передан. (optional)
     * @param  \DateTime|null $created_to Не раньше createdFrom, если он передан. (optional)
     * @param  \DateTime|null $completed_from Не позже completedTo, если он передан. (optional)
     * @param  \DateTime|null $completed_to Не раньше completedFrom, если он передан. (optional)
     * @param  string|null $failure_code Нормализованный код причины платежа. (optional)
     * @param  string|null $search Поиск по paymentId, orderId и описанию платежа. (optional)
     * @param  string|null $sort (optional, default to 'createdAt')
     * @param  string|null $sort_direction (optional, default to 'desc')
     * @param  string|null $cursor Непрозрачный курсор из предыдущего ответа. Используйте только с теми же фильтрами и сортировкой. При одинаковом sort key API использует стабильный вторичный ID. (optional)
     * @param  int|null $limit Количество записей в ответе. (optional, default to 20)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listPayments'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listPaymentsAsyncWithHttpInfo($order_id = null, $status = null, $payment_method = null, $amount_from = null, $amount_to = null, $created_from = null, $created_to = null, $completed_from = null, $completed_to = null, $failure_code = null, $search = null, $sort = 'createdAt', $sort_direction = 'desc', $cursor = null, $limit = 20, string $contentType = self::contentTypes['listPayments'][0])
    {
        $returnType = '\OPayments\SDK\Model\PaymentList';
        $request = $this->listPaymentsRequest($order_id, $status, $payment_method, $amount_from, $amount_to, $created_from, $created_to, $completed_from, $completed_to, $failure_code, $search, $sort, $sort_direction, $cursor, $limit, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'listPayments'
     *
     * @param  string|null $order_id Идентификатор заказа в системе мерчанта. (optional)
     * @param  string[]|null $status (optional)
     * @param  string|null $payment_method (optional)
     * @param  int|null $amount_from Не больше amountTo, если он передан. (optional)
     * @param  int|null $amount_to Не меньше amountFrom, если он передан. (optional)
     * @param  \DateTime|null $created_from Не позже createdTo, если он передан. (optional)
     * @param  \DateTime|null $created_to Не раньше createdFrom, если он передан. (optional)
     * @param  \DateTime|null $completed_from Не позже completedTo, если он передан. (optional)
     * @param  \DateTime|null $completed_to Не раньше completedFrom, если он передан. (optional)
     * @param  string|null $failure_code Нормализованный код причины платежа. (optional)
     * @param  string|null $search Поиск по paymentId, orderId и описанию платежа. (optional)
     * @param  string|null $sort (optional, default to 'createdAt')
     * @param  string|null $sort_direction (optional, default to 'desc')
     * @param  string|null $cursor Непрозрачный курсор из предыдущего ответа. Используйте только с теми же фильтрами и сортировкой. При одинаковом sort key API использует стабильный вторичный ID. (optional)
     * @param  int|null $limit Количество записей в ответе. (optional, default to 20)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listPayments'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listPaymentsRequest($order_id = null, $status = null, $payment_method = null, $amount_from = null, $amount_to = null, $created_from = null, $created_to = null, $completed_from = null, $completed_to = null, $failure_code = null, $search = null, $sort = 'createdAt', $sort_direction = 'desc', $cursor = null, $limit = 20, string $contentType = self::contentTypes['listPayments'][0])
    {

        if ($order_id !== null && strlen($order_id) > 128) {
            throw new \InvalidArgumentException('invalid length for "$order_id" when calling PaymentsApi.listPayments, must be smaller than or equal to 128.');
        }
        


        if ($amount_from !== null && $amount_from < 1) {
            throw new \InvalidArgumentException('invalid value for "$amount_from" when calling PaymentsApi.listPayments, must be bigger than or equal to 1.');
        }
        
        if ($amount_to !== null && $amount_to < 1) {
            throw new \InvalidArgumentException('invalid value for "$amount_to" when calling PaymentsApi.listPayments, must be bigger than or equal to 1.');
        }
        




        if ($failure_code !== null && strlen($failure_code) > 128) {
            throw new \InvalidArgumentException('invalid length for "$failure_code" when calling PaymentsApi.listPayments, must be smaller than or equal to 128.');
        }
        
        if ($search !== null && strlen($search) > 128) {
            throw new \InvalidArgumentException('invalid length for "$search" when calling PaymentsApi.listPayments, must be smaller than or equal to 128.');
        }
        



        if ($limit !== null && $limit > 100) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling PaymentsApi.listPayments, must be smaller than or equal to 100.');
        }
        if ($limit !== null && $limit < 1) {
            throw new \InvalidArgumentException('invalid value for "$limit" when calling PaymentsApi.listPayments, must be bigger than or equal to 1.');
        }
        

        $resourcePath = '/payments';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $order_id,
            'orderId', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $status,
            'status', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $payment_method,
            'paymentMethod', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $amount_from,
            'amountFrom', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $amount_to,
            'amountTo', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $created_from,
            'createdFrom', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $created_to,
            'createdTo', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $completed_from,
            'completedFrom', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $completed_to,
            'completedTo', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $failure_code,
            'failureCode', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $search,
            'search', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort,
            'sort', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort_direction,
            'sortDirection', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $cursor,
            'cursor', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $limit,
            'limit', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                try {
                    $httpBody = json_encode($formParams, JSON_THROW_ON_ERROR);
                } catch (\JsonException $e) {
                    throw new \InvalidArgumentException('json_encode error: ' . $e->getMessage(), 0, $e);
                }
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Signature');
        if ($apiKey !== null) {
            $headers['X-Signature'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Identity');
        if ($apiKey !== null) {
            $headers['X-Identity'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        if ($this->config->getCertFile()) {
            $options[RequestOptions::CERT] = $this->config->getCertFile();
        }

        if ($this->config->getKeyFile()) {
            $options[RequestOptions::SSL_KEY] = $this->config->getKeyFile();
        }

        return $options;
    }

    private function handleResponseWithDataType(
        string $dataType,
        RequestInterface $request,
        ResponseInterface $response
    ): array {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody(); //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $request->getUri()
                        ),
                        $response->getStatusCode(),
                        $response->getHeaders(),
                        $content
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $dataType, []),
            $response->getStatusCode(),
            $response->getHeaders()
        ];
    }

    private function responseWithinRangeCode(
        string $rangeCode,
        int $statusCode
    ): bool {
        $left = (int) ($rangeCode[0].'00');
        $right = (int) ($rangeCode[0].'99');

        return $statusCode >= $left && $statusCode <= $right;
    }
}
