<?php
/**
 * DeviceData
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OPayments\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OPayments API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OPayments\SDK\Model;

use \ArrayAccess;
use \OPayments\SDK\ObjectSerializer;

/**
 * DeviceData Class Doc Comment
 *
 * @category Class
 * @package  OPayments\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DeviceData implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'DeviceData';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'platform_type' => 'string',
        'os' => 'string',
        'browser' => 'string',
        'language' => 'string',
        'timezone_name' => 'string',
        'user_agent' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'platform_type' => null,
        'os' => null,
        'browser' => null,
        'language' => null,
        'timezone_name' => null,
        'user_agent' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'platform_type' => false,
        'os' => false,
        'browser' => false,
        'language' => false,
        'timezone_name' => false,
        'user_agent' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'platform_type' => 'platformType',
        'os' => 'os',
        'browser' => 'browser',
        'language' => 'language',
        'timezone_name' => 'timezoneName',
        'user_agent' => 'userAgent'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'platform_type' => 'setPlatformType',
        'os' => 'setOs',
        'browser' => 'setBrowser',
        'language' => 'setLanguage',
        'timezone_name' => 'setTimezoneName',
        'user_agent' => 'setUserAgent'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'platform_type' => 'getPlatformType',
        'os' => 'getOs',
        'browser' => 'getBrowser',
        'language' => 'getLanguage',
        'timezone_name' => 'getTimezoneName',
        'user_agent' => 'getUserAgent'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    public const PLATFORM_TYPE_MOBILE = 'mobile';
    public const PLATFORM_TYPE_DESKTOP = 'desktop';

    /**
     * Gets allowable values of the enum
     *
     * @return string[]
     */
    public function getPlatformTypeAllowableValues()
    {
        return [
            self::PLATFORM_TYPE_MOBILE,
            self::PLATFORM_TYPE_DESKTOP,
        ];
    }

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('platform_type', $data ?? [], null);
        $this->setIfExists('os', $data ?? [], null);
        $this->setIfExists('browser', $data ?? [], null);
        $this->setIfExists('language', $data ?? [], null);
        $this->setIfExists('timezone_name', $data ?? [], null);
        $this->setIfExists('user_agent', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        $allowedValues = $this->getPlatformTypeAllowableValues();
        if (!is_null($this->container['platform_type']) && !in_array($this->container['platform_type'], $allowedValues, true)) {
            $invalidProperties[] = sprintf(
                "invalid value '%s' for 'platform_type', must be one of '%s'",
                $this->container['platform_type'],
                implode("', '", $allowedValues)
            );
        }

        if (!is_null($this->container['os']) && (mb_strlen($this->container['os']) > 64)) {
            $invalidProperties[] = "invalid value for 'os', the character length must be smaller than or equal to 64.";
        }

        if (!is_null($this->container['os']) && (mb_strlen($this->container['os']) < 1)) {
            $invalidProperties[] = "invalid value for 'os', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['browser']) && (mb_strlen($this->container['browser']) > 64)) {
            $invalidProperties[] = "invalid value for 'browser', the character length must be smaller than or equal to 64.";
        }

        if (!is_null($this->container['browser']) && (mb_strlen($this->container['browser']) < 1)) {
            $invalidProperties[] = "invalid value for 'browser', the character length must be bigger than or equal to 1.";
        }

        if (!is_null($this->container['language']) && (mb_strlen($this->container['language']) > 64)) {
            $invalidProperties[] = "invalid value for 'language', the character length must be smaller than or equal to 64.";
        }

        if (!is_null($this->container['timezone_name']) && (mb_strlen($this->container['timezone_name']) > 128)) {
            $invalidProperties[] = "invalid value for 'timezone_name', the character length must be smaller than or equal to 128.";
        }

        if (!is_null($this->container['user_agent']) && (mb_strlen($this->container['user_agent']) > 1024)) {
            $invalidProperties[] = "invalid value for 'user_agent', the character length must be smaller than or equal to 1024.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets platform_type
     *
     * @return string|null
     */
    public function getPlatformType()
    {
        return $this->container['platform_type'];
    }

    /**
     * Sets platform_type
     *
     * @param string|null $platform_type platform_type
     *
     * @return self
     */
    public function setPlatformType($platform_type)
    {
        if (is_null($platform_type)) {
            throw new \InvalidArgumentException('non-nullable platform_type cannot be null');
        }
        $allowedValues = $this->getPlatformTypeAllowableValues();
        if (!in_array($platform_type, $allowedValues, true)) {
            throw new \InvalidArgumentException(
                sprintf(
                    "Invalid value '%s' for 'platform_type', must be one of '%s'",
                    $platform_type,
                    implode("', '", $allowedValues)
                )
            );
        }
        $this->container['platform_type'] = $platform_type;

        return $this;
    }

    /**
     * Gets os
     *
     * @return string|null
     */
    public function getOs()
    {
        return $this->container['os'];
    }

    /**
     * Sets os
     *
     * @param string|null $os os
     *
     * @return self
     */
    public function setOs($os)
    {
        if (is_null($os)) {
            throw new \InvalidArgumentException('non-nullable os cannot be null');
        }
        if ((mb_strlen($os) > 64)) {
            throw new \InvalidArgumentException('invalid length for $os when calling DeviceData., must be smaller than or equal to 64.');
        }
        if ((mb_strlen($os) < 1)) {
            throw new \InvalidArgumentException('invalid length for $os when calling DeviceData., must be bigger than or equal to 1.');
        }

        $this->container['os'] = $os;

        return $this;
    }

    /**
     * Gets browser
     *
     * @return string|null
     */
    public function getBrowser()
    {
        return $this->container['browser'];
    }

    /**
     * Sets browser
     *
     * @param string|null $browser browser
     *
     * @return self
     */
    public function setBrowser($browser)
    {
        if (is_null($browser)) {
            throw new \InvalidArgumentException('non-nullable browser cannot be null');
        }
        if ((mb_strlen($browser) > 64)) {
            throw new \InvalidArgumentException('invalid length for $browser when calling DeviceData., must be smaller than or equal to 64.');
        }
        if ((mb_strlen($browser) < 1)) {
            throw new \InvalidArgumentException('invalid length for $browser when calling DeviceData., must be bigger than or equal to 1.');
        }

        $this->container['browser'] = $browser;

        return $this;
    }

    /**
     * Gets language
     *
     * @return string|null
     */
    public function getLanguage()
    {
        return $this->container['language'];
    }

    /**
     * Sets language
     *
     * @param string|null $language language
     *
     * @return self
     */
    public function setLanguage($language)
    {
        if (is_null($language)) {
            throw new \InvalidArgumentException('non-nullable language cannot be null');
        }
        if ((mb_strlen($language) > 64)) {
            throw new \InvalidArgumentException('invalid length for $language when calling DeviceData., must be smaller than or equal to 64.');
        }

        $this->container['language'] = $language;

        return $this;
    }

    /**
     * Gets timezone_name
     *
     * @return string|null
     */
    public function getTimezoneName()
    {
        return $this->container['timezone_name'];
    }

    /**
     * Sets timezone_name
     *
     * @param string|null $timezone_name timezone_name
     *
     * @return self
     */
    public function setTimezoneName($timezone_name)
    {
        if (is_null($timezone_name)) {
            throw new \InvalidArgumentException('non-nullable timezone_name cannot be null');
        }
        if ((mb_strlen($timezone_name) > 128)) {
            throw new \InvalidArgumentException('invalid length for $timezone_name when calling DeviceData., must be smaller than or equal to 128.');
        }

        $this->container['timezone_name'] = $timezone_name;

        return $this;
    }

    /**
     * Gets user_agent
     *
     * @return string|null
     */
    public function getUserAgent()
    {
        return $this->container['user_agent'];
    }

    /**
     * Sets user_agent
     *
     * @param string|null $user_agent user_agent
     *
     * @return self
     */
    public function setUserAgent($user_agent)
    {
        if (is_null($user_agent)) {
            throw new \InvalidArgumentException('non-nullable user_agent cannot be null');
        }
        if ((mb_strlen($user_agent) > 1024)) {
            throw new \InvalidArgumentException('invalid length for $user_agent when calling DeviceData., must be smaller than or equal to 1024.');
        }

        $this->container['user_agent'] = $user_agent;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


