<?php
/**
 * RefundReason
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OPayments\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OPayments API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OPayments\SDK\Model;
use \OPayments\SDK\ObjectSerializer;

/**
 * RefundReason Class Doc Comment
 *
 * @category Class
 * @package  OPayments\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RefundReason
{
    /**
     * Possible values of this enum
     */
    public const REQUESTED_BY_CUSTOMER = 'requested_by_customer';

    public const DUPLICATE = 'duplicate';

    public const SUSPECTED_FRAUD = 'suspected_fraud';

    public const OTHER = 'other';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::REQUESTED_BY_CUSTOMER,
            self::DUPLICATE,
            self::SUSPECTED_FRAUD,
            self::OTHER
        ];
    }
}


