<?php
/**
 * RefundSummaryTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OPayments\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OPayments API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OPayments\SDK\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * RefundSummaryTest Class Doc Comment
 *
 * @category    Class
 * @description Суммы принятых возвратов в минимальных единицах валюты платежа. Возвраты в статусе pending не уменьшают refundableAmount.
 * @package     OPayments\SDK
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class RefundSummaryTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "RefundSummary"
     */
    public function testRefundSummary()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "refunded_amount"
     */
    public function testPropertyRefundedAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "refundable_amount"
     */
    public function testPropertyRefundableAmount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "refund_count"
     */
    public function testPropertyRefundCount()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
