<?php
/**
 * PaymentsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OPayments\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * OPayments API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OPayments\SDK\Test\Api;

use \OPayments\SDK\Configuration;
use \OPayments\SDK\ApiException;
use \OPayments\SDK\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PaymentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OPayments\SDK
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class PaymentsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for getPayment
     *
     * Получить платёж.
     *
     */
    public function testGetPayment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for listPayments
     *
     * Найти платежи.
     *
     */
    public function testListPayments()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
